spring:
  application:
    name: vendas-api

  datasource:
    url: jdbc:postgresql://localhost:5432/vendas
    username: postgres
    password: postgres
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect